### ISSUE TITLE
Require Destroy 1.0 then the mod doesn't exist yet. 

### ISSUE THREAD

**Issue by shawny43** [petrolpark/Petrols-Parts#14]
**Before submitting a bug report, ensure you are familiar with the [rules](https://github.com/petrolpark/Petrols-Parts/issues/1).** Do not include this line in the bug report.

**Describe the bug**

**To Reproduce**

Steps to reproduce the behavior. For example:

1. Install petrol parts and destroy in same modpack from Curseforge or Modrinth.
2. Run Minecraft Client
3. Found error in Forge side. 

**Expected Behavior**

Mods should recognize correctly even it's snapshot it's should suppose to run on any branch for the same version.

**Screenshots**

![image](https://github.com/user-attachments/assets/b1daac28-c128-4087-875d-305c4516c810)

**System Information**

You should only report issues on the latest version of Petrols-Parts. No others are supported. Include the following information:

 - Create version 0.5.1h
`<ul>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures">Fusion (Connected Textures) (by SuperMartijn642)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/farmers-respite">Farmer's Respite (by lumpazl)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks">Sophisticated Backpacks (by P3pp3rF1y)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-crystal-clear">Create: Crystal Clear (by singularity_cyvack)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/chisels-bits">Chisels & Bits - For Forge (by AlgorithmX2)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-stuff-additions">Create Stuff & Additions (by Furti_Two)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/steam-powered-create">Create: Steam Powered (by yuesha_yc)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cc-tweaked">CC: Tweaked (by SquidDev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry">Create Enchantment Industry (by DragonsPlus)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-framed">Create: Framed (by DakotaPrideModding)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/numismatics">Create: Numismatics (by IThundxr)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-bitterballen">Create: Bitterballen (by pyzpre)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/resourceful-lib">Resourceful Lib (by ThatGravyBoat)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-numismatics-crafting-recipe">Create: Numismatics Crafting Recipe (by Catcoll458)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/polymorph">Polymorph (Fabric/Forge/Quilt) (by TheIllusiveC4)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/curios">Curios API (Forge/NeoForge) (by TheIllusiveC4)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-power-loader">Create: Power Loader (by Lysine)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-mechanical-extruder">Create Mechanical Extruder (by oierbravo_mc)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/supplementaries">Supplementaries (by MehVahdJukaar)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/variant-chiseled-bookshelves">Variant Chiseled Bookshelves [Fabric | Forge] (by XanthianZ)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-dreams-desires">Create: Dreams & Desires (by Luna)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/embeddium">Embeddium (by embeddedt)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-gourmet">Create Gourmet (by SilverGoId)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/aquaculture-delight">Aquaculture Delight (A Farmer's Delight Add-on) (by nocubeyt)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/refurbished-furniture">MrCrayfish's Furniture Mod: Refurbished (by MrCrayfish)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/immersive-melodies">Immersive Melodies [Fabric/Forge] (by Conczin)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/petrolpark-library">Petrolpark Library (by Petrolpark)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/building-gadgets">Building Gadgets (by Direwolf20)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/builders-delight-forge">Builder's Delight (Forge) (by Tynoxs)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails">Create: Steam 'n' Rails (by IThundxr)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-cafe">Create Cafe (by Myst)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/chipped">Chipped (by terrariumearth)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/architectury-api">Architectury API (Fabric/Forge/NeoForge) (by shedaniel)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-decoration-casing">Create Decoration Casing (by TheLynkYT)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/building-but-better">Building But Better (by Starfish_Studios)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/interiors">Create: Interiors (by syslev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/createaddition">Create Crafts & Additions (by MRHminer)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ftb-ranks-forge">FTB Ranks (Forge) (by FTB)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/scorched-guns">~SCORCHED GUNS 2~  (by Ribs498)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/tacz-npcs">TACZ: Npcs (by jeducklet)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/chisel-reborn">Chisel Reborn [Forge/Fabric/NeoForge] (by Slaincow)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/essential-mod">Essential Mod (by SparkUniverse_)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/trackwork">Trackwork (by Endal)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/large-meals-an-add-on-for-farmers-delight">Large Meals (An Add-on for Farmer's Delight) (by LostWiz08)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/amendments">Amendments (by plantspookable)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-diesel-generators">Create: Diesel Generators (by george8188262)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/scorched-guns-brass">Scorched Guns: Brass (by Ribs498)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/destroy-chemistry">Destroy (by Petrolpark)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-sifting">Create Sifting (by oierbravo_mc)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-modern-train-parts">Create: Modern Train Parts (by dugske)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cc-vs">CC: VS (by TechTastic1)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/selene">Moonlight Lib (by MehVahdJukaar)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-vintage-improvements">Create: Vintage Improvements (by Negodya1)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/createstuffadditions-fix">CreateStuffAdditions Fix (by Noobanidus)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/fibers-guns-pack-for-tacz">Fibers' Guns Pack for TACZ (by FIBERS)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/athena">Athena (by CodexAdrian)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-tacz-automation">Create: TaCZ Automation (by TerraPixel)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-misc-and-things">Create : Misc & Things (by To0pa)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/createutilities">Create Utilities (Fabric/Forge) (by duquee___)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge">FTB Teams (Forge) (by FTB)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cloth-config">Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-compressed">Create Compressed (by nocubeyt)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-haven-qualities">Create: Haven Qualities (by CathieNova)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/geckolib">GeckoLib (by Gecko)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-mechanical-spawner">Create Mechanical Spawner (by oierbravo_mc)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-chunkloading">Create Chunkloading (by embeddedt)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/corail-woodcutter">Corail Woodcutter (by Corail_31)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/more-red-x-cc-tweaked-compat">More Red x CC:Tweaked Compat (by YuRaNnNzZZ)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-chromaticreturn">Create Chromatic Return (by phicctv)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-extended-cogs">Create: Extended Cogwheels  (by Rabbitminers)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/framework">Framework (by MrCrayfish)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-clockwork">Clockwork: Create x Valkyrien Skies (by rubydesic)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/farmers-structures">Farmers Structures (by BlackAuresArt)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/flywheel">Flywheel (Legacy) (by jozufozu)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-connected">Create: Connected (by Lysine)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/aquaculture">Aquaculture 2 (by Shadow)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create">Create (by simibubi)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/timeless-and-classics-zero">[TaCZ] Timeless and Classics Zero (by nekocrane)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-factory">Create: Factory (by antopfr90)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/infinitybuttons">Infinity Buttons (by LarsMans)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/timeless-and-classics-guns-lesraisins-append-pack">[TaCZ] LesRaisins Append Pack (by xjqshm)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge">Kotlin for Forge (by thedarkcolour)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-railways-navigator">Create Railways Navigator (by MrJulsen)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-industry">Create: The Factory Must Grow (by Dr_Mango_Tea)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/copycats">Create: Copycats+ (by Lysine)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/blueprint">Blueprint (by TeamAbnormals)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-recycle-everything">Create Recycle Everything (by nocubeyt)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/buildersaddition">Builders Crafts & Additions (by MRHminer)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-liquid-fuel">Create: Liquid Fuel (by Forsteri123)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/bellsandwhistles">Create: Bells & Whistles (by syslev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ftb-essentials">FTB Essentials (Forge & Fabric) (by FTB)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/protection-pixel">Create: Protection Pixel (by JEDIGD)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/more-red">More Red (by Commoble)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/eureka-ships">Eureka! Ships! for Valkyrien Skies (Forge/Fabric) (by rubydesic)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-teleporters">Create : Teleporters (by Chilllliii)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-ultimate-factory">Create: Ultimate Factory [Forge/Fabric] (by robinfrt)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/fishing-bobber-detector">Create: Fishing Bobber Detector | Automatic Fishing with Create (by GLaD0S)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cccbridge">CC:C Bridge (by Sammy_echt)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge">FTB Chunks (Forge) (by FTB)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/burnt">Burnt (by pxlbnk)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge">FTB Library (Forge) (by FTB)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/handcrafted">Handcrafted (by terrariumearth)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/farmers-plus">Farmer's Plus (by EndilCrafter)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/valkyrien-skies">Valkyrien Skies (Forge/Fabric) (by triode_)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-new-age">Create: New Age (by nullBlade)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/petrols-parts">Petrol's Parts (Create add-on) (by Petrolpark)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-sabers">Create Sabers (by Leroidesafk)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/botarium">Botarium (by CodexAdrian)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/chisel-chipped-integration">Chisel Chipped Integration (by vsemper)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-encased">Create Encased (by iglee42)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-northstar">Create: Northstar (by lightning2401)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/sophisticated-core">Sophisticated Core (by P3pp3rF1y)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-design-n-decor">Create: Design n' Decor (by MilkyFur)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/liquid-burner">Liquid Burner (by Ferri_Arnus)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/farmers-delight">Farmer's Delight (by vectorwing)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/jei">Just Enough Items (JEI) (by mezz)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/woodworks">Woodworks (by TeamAbnormals)</a></li>
</ul>
`

**Additional context**
Also, there the log. 
`---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2024-10-02 20:40:33
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.3.7-universal.jar%23401!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:138) ~[forge-1.20.1-47.3.7-universal.jar%23401!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%23396!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:421) ~[client-1.20.1-20230612.114412-srg.jar%23396!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23396!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:146) ~[forge-1.20.1-47.3.7-universal.jar%23401!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:954) ~[client-1.20.1-20230612.114412-srg.jar%23396!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23396!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23396!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.3.7.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.7.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.7.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.7.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: NONE
Stacktrace:
	at net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:63) ~[forge-1.20.1-47.3.7-universal.jar%23401!/:?] {re:classloading}
-- MOD petrolsparts --
Details:
	Mod File: /C:/Users/shawn/curseforge/minecraft/Instances/Mechanicraft/mods/petrolsparts-1.20.1-1.0.3.jar
	Failure message: Mod petrolsparts only supports destroy 0.1.0
		Currently, destroy is 0.1.0-snapshot-9
	Mod Version: 1.0.3
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE
Stacktrace:
	at net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:63) ~[forge-1.20.1-47.3.7-universal.jar%23401!/:?] {re:classloading}
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?] {}
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:61) ~[forge-1.20.1-47.3.7-universal.jar%23401!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:138) ~[forge-1.20.1-47.3.7-universal.jar%23401!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%23396!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:421) ~[client-1.20.1-20230612.114412-srg.jar%23396!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23396!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:146) ~[forge-1.20.1-47.3.7-universal.jar%23401!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:954) ~[client-1.20.1-20230612.114412-srg.jar%23396!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23396!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23396!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.3.7.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.7.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.7.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.7.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- MOD destroy --
Details:
	Mod File: /C:/Users/shawn/curseforge/minecraft/Instances/Mechanicraft/mods/destroy-1.20.1-0.1.0-snapshot-9.jar
	Failure message: Mod destroy requires petrolpark 1.0.6 or above
		Currently, petrolpark is 1.0.2
	Mod Version: 0.1.0-snapshot-9
	Mod Issue URL: https://github.com/petrolpark/Destroy/issues
	Exception message: MISSING EXCEPTION MESSAGE

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 423826184 bytes (404 MiB) / 1065353216 bytes (1016 MiB) up to 8522825728 bytes (8128 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600X 6-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.69
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon RX 6750 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x73df
	Graphics card #0 versionInfo: DriverVersion=32.0.12011.1036
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 16384.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 64937.10
	Virtual memory used (MB): 38579.29
	Swap memory total (MB): 15872.00
	Swap memory used (MB): 287.91
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8128m -Xms256m
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.3.7.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.7.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.3.7.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.3.7.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.7.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar essential-loader TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		kotlinforforge@4.11.0
		javafml@null
		lowcodefml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |NONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.20.1-47.3.7-universal.jar                 |Forge                         |forge                         |47.3.7              |NONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90`

Take note i already tested with Destroy 0.8 (Lastest stable) and the alpha (1.0 Snapshot 9) and both doesn't seem to be recognize by the client himselft due to dependency issue with Petrol parts. 

**Minecraft Username**
shawny43

If you are interested in the **Beta Tester** [Badge](https://patreon.com/petrolpark/about), include your Minecraft username here (case-sensitive).

**Comment by Explode007** [comment]
Same issue here.

**Comment by petrolpark** [comment]
Wait until Destroy 0.1.0 releases.

**Comment by CDWimmer** [comment]
See here if you want a workaround: https://github.com/petrolpark/Destroy/issues/451#issuecomment-2381317303
