### ISSUE TITLE
[Bug] creating a new world in a modpack  stucks at 100%

### ISSUE THREAD

**Issue by odiseus22** [petrolpark/Petrols-Parts#17]
hi Petrolpark, first of all, thanks for your work I realy like what you do.
I Have this error in my logs, when I try to create a new world with Petrolpark activated it stucks at 100%, seems to be an infinite loop,  it appears 48 times, I did not paste all the log because I do not know how to show only the activated mods (in the log it mentions mods that i have in cursforge, but i have them disabled, most of them)

if you need more information or want me to try diferent things I am glad to help.

the last part of the log error:

java.lang.ClassCastException: class com.petrolpark.itemdecay.DecayingItemHandler$1 cannot be cast to class com.petrolpark.itemdecay.DecayingItemHandler$ServerDecayingItemHandler (com.petrolpark.itemdecay.DecayingItemHandler$1 and com.petrolpark.itemdecay.DecayingItemHandler$ServerDecayingItemHandler are in module petrolpark@1.0.2 of loader 'TRANSFORMER' @2bd8c8f1)
	at TRANSFORMER/petrolpark@1.0.2/com.petrolpark.PetrolparkCommonEvents.onTick(PetrolparkCommonEvents.java:54)
	at TRANSFORMER/petrolpark@1.0.2/com.petrolpark.__PetrolparkCommonEvents_onTick_LevelTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.3.11/net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactory.java:930)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.md2fbe96$lambda$tickWorlds$0$5(MinecraftServer.java:7398)
	at TRANSFORMER/dimthread@1.0.5/me.srrapero720.dimthread.DimThread.swapThreadsAndRun(DimThread.java:50)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.md2fbe96$lambda$tickWorlds$1$4(MinecraftServer.java:7391)
	at TRANSFORMER/dimthread@1.0.5/me.srrapero720.dimthread.thread.ThreadPool.lambda$execute$1(ThreadPool.java:54)
	at TRANSFORMER/dimthread@1.0.5/me.srrapero720.dimthread.thread.ThreadPool.lambda$execute$0(ThreadPool.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[22:50:55] [dimthread_server_overworld/ERROR]: Exception caught during firing event: class com.petrolpark.itemdecay.DecayingItemHandler$1 cannot be cast to class com.petrolpark.itemdecay.DecayingItemHandler$ServerDecayingItemHandler (com.petrolpark.itemdecay.DecayingItemHandler$1 and com.petrolpark.itemdecay.DecayingItemHandler$ServerDecayingItemHandler are in module petrolpark@1.0.2 of loader 'TRANSFORMER' @2bd8c8f1)
	Index: 9
	Listeners:
		0: HIGH
		1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		2: NORMAL
		3: net.minecraftforge.eventbus.EventBus$$Lambda$1704/0x000000080090a438@53ccb565
		4: ASM: class com.dragonfight.event.EventHandler onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		5: net.minecraftforge.eventbus.EventBus$$Lambda$1704/0x000000080090a438@6c43b6e
		6: ASM: class com.github.alexthe666.alexsmobs.event.ServerEvents onServerTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		7: net.minecraftforge.eventbus.EventBus$$Lambda$1704/0x000000080090a438@66d0b482
		8: net.minecraftforge.eventbus.EventBus$$Lambda$1704/0x000000080090a438@2a3aec55
		9: ASM: class com.petrolpark.PetrolparkCommonEvents onTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		10: net.minecraftforge.eventbus.EventBus$$Lambda$1704/0x000000080090a438@1ceb03ea
		11: ASM: class com.aetherteam.aether.event.listeners.DimensionListener onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		12: net.minecraftforge.eventbus.EventBus$$Lambda$1704/0x000000080090a438@3bd35452
		13: ASM: class com.railwayteam.railways.forge.events.CommonEventsForge onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		14: ASM: class org.valkyrienskies.clockwork.forge.content.events.ForgeClockworkCommonEvents onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		15: ASM: class com.simibubi.create.foundation.events.CommonEvents onServerWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		16: net.minecraftforge.eventbus.EventBus$$Lambda$1704/0x000000080090a438@58c4830e
		17: ASM: com.illusivesoulworks.polymorph.common.CommonEventsListener@3c6f9bfb levelTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		18: ASM: com.natamus.collective.forge.events.RegisterCollectiveForgeEvents@44c8314f onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
java.lang.ClassCastException: class com.petrolpark.itemdecay.DecayingItemHandler$1 cannot be cast to class com.petrolpark.itemdecay.DecayingItemHandler$ServerDecayingItemHandler (com.petrolpark.itemdecay.DecayingItemHandler$1 and com.petrolpark.itemdecay.DecayingItemHandler$ServerDecayingItemHandler are in module petrolpark@1.0.2 of loader 'TRANSFORMER' @2bd8c8f1)
	at TRANSFORMER/petrolpark@1.0.2/com.petrolpark.PetrolparkCommonEvents.onTick(PetrolparkCommonEvents.java:54)
	at TRANSFORMER/petrolpark@1.0.2/com.petrolpark.__PetrolparkCommonEvents_onTick_LevelTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.3.11/net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactory.java:930)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.md2fbe96$lambda$tickWorlds$0$5(MinecraftServer.java:7398)
	at TRANSFORMER/dimthread@1.0.5/me.srrapero720.dimthread.DimThread.swapThreadsAndRun(DimThread.java:50)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.md2fbe96$lambda$tickWorlds$1$4(MinecraftServer.java:7391)
	at TRANSFORMER/dimthread@1.0.5/me.srrapero720.dimthread.thread.ThreadPool.lambda$execute$1(ThreadPool.java:54)
	at TRANSFORMER/dimthread@1.0.5/me.srrapero720.dimthread.thread.ThreadPool.lambda$execute$0(ThreadPool.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[22:50:55] [dimthread_server_overworld/INFO]: Redirecting software/bernie/geckolib/core/object/PlayState
[22:50:55] [dimthread_server_overworld/ERROR]: Exception caught during firing event: class com.petrolpark.itemdecay.DecayingItemHandler$1 cannot be cast to class com.petrolpark.itemdecay.DecayingItemHandler$ServerDecayingItemHandler (com.petrolpark.itemdecay.DecayingItemHandler$1 and com.petrolpark.itemdecay.DecayingItemHandler$ServerDecayingItemHandler are in module petrolpark@1.0.2 of loader 'TRANSFORMER' @2bd8c8f1)
	Index: 9
	Listeners:
		0: HIGH
		1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		2: NORMAL
		3: net.minecraftforge.eventbus.EventBus$$Lambda$1704/0x000000080090a438@53ccb565
		4: ASM: class com.dragonfight.event.EventHandler onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		5: net.minecraftforge.eventbus.EventBus$$Lambda$1704/0x000000080090a438@6c43b6e
		6: ASM: class com.github.alexthe666.alexsmobs.event.ServerEvents onServerTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		7: net.minecraftforge.eventbus.EventBus$$Lambda$1704/0x000000080090a438@66d0b482
		8: net.minecraftforge.eventbus.EventBus$$Lambda$1704/0x000000080090a438@2a3aec55
		9: ASM: class com.petrolpark.PetrolparkCommonEvents onTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		10: net.minecraftforge.eventbus.EventBus$$Lambda$1704/0x000000080090a438@1ceb03ea
		11: ASM: class com.aetherteam.aether.event.listeners.DimensionListener onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		12: net.minecraftforge.eventbus.EventBus$$Lambda$1704/0x000000080090a438@3bd35452
		13: ASM: class com.railwayteam.railways.forge.events.CommonEventsForge onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		14: ASM: class org.valkyrienskies.clockwork.forge.content.events.ForgeClockworkCommonEvents onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		15: ASM: class com.simibubi.create.foundation.events.CommonEvents onServerWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		16: net.minecraftforge.eventbus.EventBus$$Lambda$1704/0x000000080090a438@58c4830e
		17: ASM: com.illusivesoulworks.polymorph.common.CommonEventsListener@3c6f9bfb levelTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		18: ASM: com.natamus.collective.forge.events.RegisterCollectiveForgeEvents@44c8314f onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
java.lang.ClassCastException: class com.petrolpark.itemdecay.DecayingItemHandler$1 cannot be cast to class com.petrolpark.itemdecay.DecayingItemHandler$ServerDecayingItemHandler (com.petrolpark.itemdecay.DecayingItemHandler$1 and com.petrolpark.itemdecay.DecayingItemHandler$ServerDecayingItemHandler are in module petrolpark@1.0.2 of loader 'TRANSFORMER' @2bd8c8f1)
	at TRANSFORMER/petrolpark@1.0.2/com.petrolpark.PetrolparkCommonEvents.onTick(PetrolparkCommonEvents.java:54)
	at TRANSFORMER/petrolpark@1.0.2/com.petrolpark.__PetrolparkCommonEvents_onTick_LevelTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.3.11/net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactory.java:930)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.md2fbe96$lambda$tickWorlds$0$5(MinecraftServer.java:7398)
	at TRANSFORMER/dimthread@1.0.5/me.srrapero720.dimthread.DimThread.swapThreadsAndRun(DimThread.java:50)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.md2fbe96$lambda$tickWorlds$1$4(MinecraftServer.java:7391)
	at TRANSFORMER/dimthread@1.0.5/me.srrapero720.dimthread.thread.ThreadPool.lambda$execute$1(ThreadPool.java:54)
	at TRANSFORMER/dimthread@1.0.5/me.srrapero720.dimthread.thread.ThreadPool.lambda$execute$0(ThreadPool.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[22:50:55] [dimthread_server_overworld/ERROR]: Exception caught during firing event: class com.petrolpark.itemdecay.DecayingItemHandler$1 cannot be cast to class com.petrolpark.itemdecay.DecayingItemHandler$ServerDecayingItemHandler (com.petrolpark.itemdecay.DecayingItemHandler$1 and com.petrolpark.itemdecay.DecayingItemHandler$ServerDecayingItemHandler are in module petrolpark@1.0.2 of loader 'TRANSFORMER' @2bd8c8f1)
	Index: 9
	Listeners:
		0: HIGH
		1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		2: NORMAL
		3: net.minecraftforge.eventbus.EventBus$$Lambda$1704/0x000000080090a438@53ccb565
		4: ASM: class com.dragonfight.event.EventHandler onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		5: net.minecraftforge.eventbus.EventBus$$Lambda$1704/0x000000080090a438@6c43b6e
		6: ASM: class com.github.alexthe666.alexsmobs.event.ServerEvents onServerTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		7: net.minecraftforge.eventbus.EventBus$$Lambda$1704/0x000000080090a438@66d0b482
		8: net.minecraftforge.eventbus.EventBus$$Lambda$1704/0x000000080090a438@2a3aec55
		9: ASM: class com.petrolpark.PetrolparkCommonEvents onTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		10: net.minecraftforge.eventbus.EventBus$$Lambda$1704/0x000000080090a438@1ceb03ea
		11: ASM: class com.aetherteam.aether.event.listeners.DimensionListener onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		12: net.minecraftforge.eventbus.EventBus$$Lambda$1704/0x000000080090a438@3bd35452
		13: ASM: class com.railwayteam.railways.forge.events.CommonEventsForge onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		14: ASM: class org.valkyrienskies.clockwork.forge.content.events.ForgeClockworkCommonEvents onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		15: ASM: class com.simibubi.create.foundation.events.CommonEvents onServerWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		16: net.minecraftforge.eventbus.EventBus$$Lambda$1704/0x000000080090a438@58c4830e
		17: ASM: com.illusivesoulworks.polymorph.common.CommonEventsListener@3c6f9bfb levelTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		18: ASM: com.natamus.collective.forge.events.RegisterCollectiveForgeEvents@44c8314f onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
java.lang.ClassCastException: class com.petrolpark.itemdecay.DecayingItemHandler$1 cannot be cast to class com.petrolpark.itemdecay.DecayingItemHandler$ServerDecayingItemHandler (com.petrolpark.itemdecay.DecayingItemHandler$1 and com.petrolpark.itemdecay.DecayingItemHandler$ServerDecayingItemHandler are in module petrolpark@1.0.2 of loader 'TRANSFORMER' @2bd8c8f1)
	at TRANSFORMER/petrolpark@1.0.2/com.petrolpark.PetrolparkCommonEvents.onTick(PetrolparkCommonEvents.java:54)
	at TRANSFORMER/petrolpark@1.0.2/com.petrolpark.__PetrolparkCommonEvents_onTick_LevelTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.3.11/net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactory.java:930)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.md2fbe96$lambda$tickWorlds$0$5(MinecraftServer.java:7398)
	at TRANSFORMER/dimthread@1.0.5/me.srrapero720.dimthread.DimThread.swapThreadsAndRun(DimThread.java:50)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.md2fbe96$lambda$tickWorlds$1$4(MinecraftServer.java:7391)
	at TRANSFORMER/dimthread@1.0.5/me.srrapero720.dimthread.thread.ThreadPool.lambda$execute$1(ThreadPool.java:54)
	at TRANSFORMER/dimthread@1.0.5/me.srrapero720.dimthread.thread.ThreadPool.lambda$execute$0(ThreadPool.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[22:50:55] [Netty Local Client IO #0/INFO]: Connected to a modded server.
[22:50:55] [Netty Local Client IO #0/INFO]: Redirecting net/minecraft/client/multiplayer/ClientRegistryLayer
[22:51:34] [Render thread/INFO]: Stopping!
[22:51:34] [Render thread/INFO]: Shutting down renderer (forge)
[22:51:34] [Render thread/INFO]: Renderer shutting down.

**Comment by odiseus22** [comment]
it seems to be a imcompatiblity with Dimensional Threading Reforked  dimthread-1.20.1-v1.0.5, i tryed to disable that one and it started to work, something strange is that i have the aether installed but disabled and i do not know why it appears in that log error

**Comment by odiseus22** [comment]
I tested only  threads + with the Petrol's Parts and for me its posible to replicate
install Petrol's Parts and Dimensional Threading Reforked in new modpack, try to create new world on creative, and hard, it will stuck at 100%
